language: python
python:
  - '3.4'
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pep8
before_install:
  - pip install -U coveralls pip pytest pytest-cov setuptools wheel tox
script:
  - tox
after_success:
  - coveralls
notifications:
  irc:
    channels: "irc.freenode.org#atal-dev"
    on_success: change
    on_failure: change
before_deploy:
- python setup.py build sdist bdist_wheel
- if [ "x" == "$(grep $(git tag -l --points-at=HEAD) setup.py)x" ]; then echo 'new tag does not exist in setup.py; bailing!'; exit 1; else echo "tag found in setup.py"; fi
deploy:
  - provider: pypi
    user: atal
    password:
      secure: TMT7jKYcIocBwJuLHCKZ2Vph7nVsylYPHVIULogKO6AyUepNjljgeUFBZLsWR6diEdEF3ILHCplInoPAa9ZuZazWlADyT+I0BmazVWrAdeVPQa+CDcNeHjxOmJczeSxTO3HAIUvwOsgj0jE8Ecf30xS/dAmzvDmhj71tvU/JrhU=
    on:
      tags: true
      repo: a-tal/ddate
      condition: $TOXENV = py34
  - provider: releases
    api_key:
      secure: "fa8RqW0GdsddFzQF063Eud6Qy5ZZhild4NmocdN6qHkehjJL0zq+Y0nyCUlNASUq4aSYsZaSqfeZxosZ/7Qj1xBinxcqeeY65reYN5kNAtgy/+AdN3HyXkNGNjMzPKqzvHygisdCJr8XTIlrne/aLJvILiSl+ZXIjPQu6KjYNDw="
    file: "/home/travis/build/a-tal/ddate/dist/ddate*.whl"
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
      condition: $TOXENV = py34
