language: python
python:
  - '3.4'
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=pep8
before_install:
  - pip install -U coveralls pip pytest pytest-cov setuptools wheel tox
script:
  - tox
after_success:
  - coveralls
notifications:
  irc:
    channels: "irc.freenode.org#atal-dev"
    on_success: change
    on_failure: change
before_deploy:
- python setup.py build sdist bdist_wheel
- if [ "x" == "$(grep $(git tag -l --points-at=HEAD) setup.py)x" ]; then echo 'new tag does not exist in setup.py; bailing!'; exit 1; else echo "tag found in setup.py"; fi
deploy:
  - provider: pypi
    user: atal
    skip_cleanup: true
    distributions: "sdist bdist_wheel"
    password:
      secure: "cVQwCXY6QwnqduNMD363+mHA37mxJKagoEh2RVSj7hQJsQWnYH5bAZrwknrx71Ux+n+22aD12lCBZEnj2qDvG68zlV4L264nfXEJqTrMP2BQrKqepubkUcuCFogxWSY4MBMvQHyhyL3u3TEsawKEKlkd5dNhxN2A/AJf2Gl/RmY="
    on:
      tags: true
      repo: a-tal/ddate
      condition: $TOXENV = py35
  - provider: releases
    api_key:
      secure: "A0yCB43R5JZxox/OLJePBNAjWgBIdjgXFMzBKiySaRdbVAAVix1JOd+2fHN6l+sKO+Yi3XPgwOmvnkz8QuMB4O2go+UGh2w+bM9WB+Lr3JA/z2eJjdyXMXqB15+jdVOLINstlHNEikJpnmCq9zvXAX+75pCnFj24EilmA8UbZAo="
    file: "/home/travis/build/a-tal/ddate/dist/ddate*.whl"
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
      condition: $TOXENV = py35
